#define ERROR                           1
#define OR                              2
#define XOR                             3
#define AND                             4
#define NOT                             5
#define NEAR                            6
#define ADJ                             7
#define LOVE                            8
#define HATE                            9
#define SYNONYM                        10
#define TERM                           11
#define GROUP_TERM                     12
#define PHR_TERM                       13
#define WILD_TERM                      14
#define PARTIAL_TERM                   15
#define BOOLEAN_FILTER                 16
#define RANGE_START                    17
#define RANGE_END                      18
#define QUOTE                          19
#define BRA                            20
#define KET                            21
