/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.0.11/xapian/xapian-core/tests/collate-apitest - do not modify directly! */
extern bool test_lockfileumask1();
extern bool test_totaldoclen1();
