/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.0.11/xapian/xapian-core/tests/collate-apitest - do not modify directly! */
extern bool test_spell1();
extern bool test_spell2();
extern bool test_spell3();
extern bool test_spell4();
extern bool test_spell5();
extern bool test_spell6();
