/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.0.11/xapian/xapian-core/tests/collate-apitest - do not modify directly! */
extern bool test_utf8iterator1();
extern bool test_utf8iterator2();
extern bool test_unicode1();
extern bool test_caseconvert1();
