/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Xapian_WRAP_H_
#define SWIG_Xapian_WRAP_H_

class SwigDirector_MatchDecider : public Xapian::MatchDecider, public Swig::Director {

public:
    SwigDirector_MatchDecider();
    virtual bool operator ()(Xapian::Document const &doc) const;
    virtual ~SwigDirector_MatchDecider();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackApply);

private:
    SWIG_Callback0_t swig_callbackApply;
    void swig_init_callbacks();
};

class SwigDirector_ExpandDecider : public Xapian::ExpandDecider, public Swig::Director {

public:
    SwigDirector_ExpandDecider();
    virtual bool operator ()(std::string const &term) const;
    virtual ~SwigDirector_ExpandDecider();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(char *);
    void swig_connect_director(SWIG_Callback0_t callbackApply);

private:
    SWIG_Callback0_t swig_callbackApply;
    void swig_init_callbacks();
};

class SwigDirector_Stopper : public Xapian::Stopper, public Swig::Director {

public:
    SwigDirector_Stopper();
    virtual bool operator ()(std::string const &term) const;
    virtual ~SwigDirector_Stopper();
    virtual std::string get_description() const;

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(char *);
    typedef char * (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackApply, SWIG_Callback1_t callbackGetDescription);

private:
    SWIG_Callback0_t swig_callbackApply;
    SWIG_Callback1_t swig_callbackGetDescription;
    void swig_init_callbacks();
};

struct SwigDirector_ValueRangeProcessor : public Xapian::ValueRangeProcessor, public Swig::Director {

public:
    SwigDirector_ValueRangeProcessor();
    virtual ~SwigDirector_ValueRangeProcessor();
    virtual Xapian::valueno operator ()(std::string &begin, std::string &end);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackApply);

private:
    SWIG_Callback0_t swig_callbackApply;
    void swig_init_callbacks();
};

class SwigDirector_Sorter : public Xapian::Sorter, public Swig::Director {

public:
    SwigDirector_Sorter();
    virtual std::string operator ()(Xapian::Document const &doc) const;
    virtual ~SwigDirector_Sorter();

    typedef char * (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackApply);

private:
    SWIG_Callback0_t swig_callbackApply;
    void swig_init_callbacks();
};


#endif
