/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class BM25Weight extends Weight {
  private long swigCPtr;

  protected BM25Weight(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.SWIGBM25WeightUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BM25Weight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      XapianJNI.delete_BM25Weight(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public BM25Weight(double k1_, double k2_, double k3_, double b_, double min_normlen_) {
    this(XapianJNI.new_BM25Weight__SWIG_0(k1_, k2_, k3_, b_, min_normlen_), true);
  }

  public BM25Weight() {
    this(XapianJNI.new_BM25Weight__SWIG_1(), true);
  }

  public BM25Weight cloneWeight() {
    long cPtr = XapianJNI.BM25Weight_cloneWeight(swigCPtr, this);
    return (cPtr == 0) ? null : new BM25Weight(cPtr, false);
  }

  public String name() {
    return XapianJNI.BM25Weight_name(swigCPtr, this);
  }

  public String serialise() {
    return XapianJNI.BM25Weight_serialise(swigCPtr, this);
  }

  public Weight unserialise(String s) {
    long cPtr = XapianJNI.BM25Weight_unserialise(swigCPtr, this, s);
    return (cPtr == 0) ? null : new BM25Weight(cPtr, false);
  }

  public double getSumPart(long wdf, double len) {
    return XapianJNI.BM25Weight_getSumPart(swigCPtr, this, wdf, len);
  }

  public double getMaxPart() {
    return XapianJNI.BM25Weight_getMaxPart(swigCPtr, this);
  }

  public double getSumExtra(double len) {
    return XapianJNI.BM25Weight_getSumExtra(swigCPtr, this, len);
  }

  public double getMaxExtra() {
    return XapianJNI.BM25Weight_getMaxExtra(swigCPtr, this);
  }

  public boolean getSumPartNeedsDocLength() {
    return XapianJNI.BM25Weight_getSumPartNeedsDocLength(swigCPtr, this);
  }

}
