/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DateValueRangeProcessor extends ValueRangeProcessor {
  private long swigCPtr;

  protected DateValueRangeProcessor(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.SWIGDateValueRangeProcessorUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DateValueRangeProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      XapianJNI.delete_DateValueRangeProcessor(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public DateValueRangeProcessor(int valno_, boolean prefer_mdy_, int epoch_year_) {
    this(XapianJNI.new_DateValueRangeProcessor__SWIG_0(valno_, prefer_mdy_, epoch_year_), true);
  }

  public DateValueRangeProcessor(int valno_, boolean prefer_mdy_) {
    this(XapianJNI.new_DateValueRangeProcessor__SWIG_1(valno_, prefer_mdy_), true);
  }

  public DateValueRangeProcessor(int valno_) {
    this(XapianJNI.new_DateValueRangeProcessor__SWIG_2(valno_), true);
  }

  public int apply(SWIGTYPE_p_std__string begin, SWIGTYPE_p_std__string end) {
    return XapianJNI.DateValueRangeProcessor_apply(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(begin), SWIGTYPE_p_std__string.getCPtr(end));
  }

}
