/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MatchDecider {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MatchDecider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MatchDecider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      XapianJNI.delete_MatchDecider(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XapianJNI.MatchDecider_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XapianJNI.MatchDecider_change_ownership(this, swigCPtr, true);
  }

  public boolean accept(Document doc) {
    return XapianJNI.MatchDecider_accept(swigCPtr, this, Document.getCPtr(doc), doc);
  }

  public MatchDecider() {
    this(XapianJNI.new_MatchDecider(), true);
    XapianJNI.MatchDecider_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
