/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Quartz {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Quartz(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Quartz obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  public static Database open(String dir) {
    return new Database(XapianJNI.Quartz_open__SWIG_0(dir), true);
  }

  public static WritableDatabase open(String dir, int action, int block_size) {
    return new WritableDatabase(XapianJNI.Quartz_open__SWIG_1(dir, action, block_size), true);
  }

  public static WritableDatabase open(String dir, int action) {
    return new WritableDatabase(XapianJNI.Quartz_open__SWIG_2(dir, action), true);
  }

}
