/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Stem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Stem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      XapianJNI.delete_Stem(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Stem(String language) {
    this(XapianJNI.new_Stem(language), true);
  }

  public String apply(String word) {
    return XapianJNI.Stem_apply(swigCPtr, this, word);
  }

  public String toString() {
    return XapianJNI.Stem_toString(swigCPtr, this);
  }

  public static String getAvailableLanguages() {
    return XapianJNI.Stem_getAvailableLanguages();
  }

}
