/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class StringValueRangeProcessor extends ValueRangeProcessor {
  private long swigCPtr;

  protected StringValueRangeProcessor(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.SWIGStringValueRangeProcessorUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringValueRangeProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      XapianJNI.delete_StringValueRangeProcessor(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public StringValueRangeProcessor(int valno_) {
    this(XapianJNI.new_StringValueRangeProcessor(valno_), true);
  }

  public int apply(SWIGTYPE_p_std__string arg0, SWIGTYPE_p_std__string arg1) {
    return XapianJNI.StringValueRangeProcessor_apply(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(arg0), SWIGTYPE_p_std__string.getCPtr(arg1));
  }

}
