/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TradWeight extends Weight {
  private long swigCPtr;

  protected TradWeight(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.SWIGTradWeightUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TradWeight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      XapianJNI.delete_TradWeight(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public TradWeight(double k) {
    this(XapianJNI.new_TradWeight__SWIG_0(k), true);
  }

  public TradWeight() {
    this(XapianJNI.new_TradWeight__SWIG_1(), true);
  }

  public TradWeight cloneWeight() {
    long cPtr = XapianJNI.TradWeight_cloneWeight(swigCPtr, this);
    return (cPtr == 0) ? null : new TradWeight(cPtr, false);
  }

  public String name() {
    return XapianJNI.TradWeight_name(swigCPtr, this);
  }

  public String serialise() {
    return XapianJNI.TradWeight_serialise(swigCPtr, this);
  }

  public Weight unserialise(String s) {
    long cPtr = XapianJNI.TradWeight_unserialise(swigCPtr, this, s);
    return (cPtr == 0) ? null : new TradWeight(cPtr, false);
  }

  public double getSumPart(long wdf, double len) {
    return XapianJNI.TradWeight_getSumPart(swigCPtr, this, wdf, len);
  }

  public double getMaxPart() {
    return XapianJNI.TradWeight_getMaxPart(swigCPtr, this);
  }

  public double getSumExtra(double len) {
    return XapianJNI.TradWeight_getSumExtra(swigCPtr, this, len);
  }

  public double getMaxExtra() {
    return XapianJNI.TradWeight_getMaxExtra(swigCPtr, this);
  }

  public boolean getSumPartNeedsDocLength() {
    return XapianJNI.TradWeight_getSumPartNeedsDocLength(swigCPtr, this);
  }

}
