/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Weight {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Weight(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Weight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      XapianJNI.delete_Weight(swigCPtr);
    }
    swigCPtr = 0;
  }

  public String name() {
    return XapianJNI.Weight_name(swigCPtr, this);
  }

  public String serialise() {
    return XapianJNI.Weight_serialise(swigCPtr, this);
  }

  public Weight unserialise(String s) {
    long cPtr = XapianJNI.Weight_unserialise(swigCPtr, this, s);
    return (cPtr == 0) ? null : new Weight(cPtr, false);
  }

  public double getSumPart(long wdf, double len) {
    return XapianJNI.Weight_getSumPart(swigCPtr, this, wdf, len);
  }

  public double getMaxPart() {
    return XapianJNI.Weight_getMaxPart(swigCPtr, this);
  }

  public double getSumExtra(double len) {
    return XapianJNI.Weight_getSumExtra(swigCPtr, this, len);
  }

  public double getMaxExtra() {
    return XapianJNI.Weight_getMaxExtra(swigCPtr, this);
  }

  public boolean getSumPartNeedsDocLength() {
    return XapianJNI.Weight_getSumPartNeedsDocLength(swigCPtr, this);
  }

}
