/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.32
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Xapian implements XapianConstants {
  public static int getBAD_VALUENO() {
    return XapianJNI.BAD_VALUENO_get();
  }

  public static String xapianVersionString() {
    return XapianJNI.xapianVersionString();
  }

  public static int xapianMajorVersion() {
    return XapianJNI.xapianMajorVersion();
  }

  public static int xapianMinorVersion() {
    return XapianJNI.xapianMinorVersion();
  }

  public static int xapianRevision() {
    return XapianJNI.xapianRevision();
  }

  public static String sortableSerialise(double value) {
    return XapianJNI.sortableSerialise(value);
  }

  public static double sortableUnserialise(String value) {
    return XapianJNI.sortableUnserialise(value);
  }

}
